[package]
name = "temp_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.7.2"
candle-datasets = "0.7.2"
candle-nn = "0.7.2"
colored = "2.1.0"
image = "0.25.2"
prettytable = "0.10.0"
rand = "0.8.5"
